[package]
name = "clipboard"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
color-eyre = "0.6.5"
console_error_panic_hook.workspace = true
ratatui = { version = "0.30.0", default-features = false, features = ["layout-cache"] }
ratzilla.workspace = true
examples-shared.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Clipboard"] }

