[workspace]
resolver = "2"
members = [
    "animations",
    "canvas_stress_test",
    "canvas_waves",
    "clipboard",
    "colors_rgb",
    "demo",
    "demo2",
    "minimal",
    "pong",
    "shared",
    "tauri",
    "text_area",
    "user_input",
    "unicode",
    "website",
    "world_map",
]
exclude = [
    "tauri/src-tauri",
]

[workspace.dependencies]
ratzilla = { path = "../" }
examples-shared = { path = "shared" }
console_error_panic_hook = "0.1.7"
tachyonfx = { version = "0.22.0", default-features = false, features = ["web-time"] }
web-time = "1.1.0"
palette = "0.7.6"
rand = { version = "0.9.2", default-features = false }
wasm-bindgen = "0.2.104"
wasm-bindgen-futures = "0.4.54"
web-sys = "0.3.81"

[patch.crates-io]
# remove this after ratatui gets updated upstream
tui-textarea = { git = "https://github.com/0xferrous/tui-textarea", rev = "b6bf812d1f5edab4f311f56d405a47341e9423cf" }
